# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 19:05
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must have 8-9 digits and must be in format AAXXXXXXXXX', regex='^(\\d{2})(\\d{8,9})$')])),
                ('destination', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must have 8-9 digits and must be in format AAXXXXXXXXX', regex='^(\\d{2})(\\d{8,9})$')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
            },
        ),
        migrations.CreateModel(
            name='EndRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ends_at', to='main.Call')),
            ],
            options={
                'verbose_name': 'End',
                'verbose_name_plural': 'End records',
            },
        ),
        migrations.CreateModel(
            name='StartRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starts_at', to='main.Call')),
            ],
            options={
                'verbose_name': 'Start',
                'verbose_name_plural': 'Start records',
            },
        ),
    ]
